"""
Cobweb / Market Feedback Simulation Module
Simulates aggregate supply shift when farmers adopt recommended crop portfolios.
Adjusts expected market price according to price elasticity of demand:
  ΔP / P = (1 / Elasticity) * (ΔS / S_baseline)
Protects farmers from collective market gluts and price crashes.
"""

import numpy as np

# Standard agricultural price elasticity of demand (inelastic: -0.4 to -0.7)
DEFAULT_ELASTICITY = -0.55

# Baseline regional supply proxy (Tonnes per district/region)
BASELINE_REGIONAL_SUPPLY = {
    "Rice": 45000.0,
    "Wheat": 40000.0,
    "Maize": 25000.0,
    "Cotton": 18000.0,
    "Sugarcane": 180000.0,
    "Soyabean": 22000.0,
    "Groundnut": 20000.0,
    "Bajra": 22000.0,
    "Jowar": 18000.0,
    "Gram": 20000.0
}

# Regional representative cluster area (hectares of active farmland in cluster)
REGIONAL_CLUSTER_HECTARES = 5000.0

class CobwebSimulator:
    def __init__(self, elasticity: float = DEFAULT_ELASTICITY):
        self.elasticity = elasticity

    def simulate_feedback(self, crop: str, base_price_rs_tonne: float, yield_tonnes_ha: float, 
                          portfolio_share: float = 1.0, adoption_rate: float = 0.3):
        """
        Calculates adjusted price under a simulated adoption scenario.
        
        Args:
            crop: crop name
            base_price_rs_tonne: initial predicted mandi price (Rs/Tonne)
            yield_tonnes_ha: predicted yield (Tonnes/ha)
            portfolio_share: fraction of farm allocated to this crop (0 to 1)
            adoption_rate: percentage of regional farmers following the advice (0 to 1)
        """
        s_base = BASELINE_REGIONAL_SUPPLY.get(crop, 25000.0)
        
        # Additional supply generated by adoption across the regional cluster
        additional_area = REGIONAL_CLUSTER_HECTARES * portfolio_share * adoption_rate
        additional_supply = additional_area * yield_tonnes_ha
        
        supply_change_pct = additional_supply / max(1.0, s_base)
        
        # Price elasticity formula: % delta P = (1 / elasticity) * % delta S
        # Since elasticity is negative, price decreases as supply increases
        price_change_pct = (1.0 / self.elasticity) * supply_change_pct
        
        # Cap maximum drop at -45% to reflect minimum support prices (MSP) / floor
        price_change_pct = max(-0.45, price_change_pct)
        
        adjusted_price = base_price_rs_tonne * (1.0 + price_change_pct)
        adjusted_price = max(base_price_rs_tonne * 0.55, adjusted_price)
        
        return {
            "crop": crop,
            "adoption_rate_pct": round(adoption_rate * 100.0, 1),
            "base_price_rs_tonne": round(base_price_rs_tonne, 1),
            "adjusted_price_rs_tonne": round(adjusted_price, 1),
            "price_drop_pct": round(abs(price_change_pct) * 100.0, 2),
            "additional_supply_tonnes": round(additional_supply, 1),
            "market_supply_pct_increase": round(supply_change_pct * 100.0, 2)
        }

    def simulate_all_scenarios(self, crop: str, base_price_rs_tonne: float, yield_tonnes_ha: float, portfolio_share: float = 1.0):
        """Simulates across standard adoption rates: 0%, 10%, 30%, 60%, 100%."""
        scenarios = [0.0, 0.10, 0.30, 0.60, 1.00]
        results = []
        for rate in scenarios:
            res = self.simulate_feedback(crop, base_price_rs_tonne, yield_tonnes_ha, portfolio_share, rate)
            results.append(res)
        return results

if __name__ == "__main__":
    sim = CobwebSimulator()
    print("Market Feedback simulation for Maize (Base Price: ₹33,675/t, Yield: 4.5 t/ha):")
    for r in sim.simulate_all_scenarios("Maize", 33675.0, 4.5, 0.6):
        print(f"  Adoption: {r['adoption_rate_pct']:4}% | Added Supply: {r['additional_supply_tonnes']:6.0f}t | Adj Price: ₹{r['adjusted_price_rs_tonne']:,.0f}/t (-{r['price_drop_pct']}%)")
